version: '3.7'

services:
  template.webapi:
    image: ${DOCKER_REGISTRY-}template
    build:
      context: .
      dockerfile: src/Template.WebApi/Dockerfile

  template.messageprocessor:
    image: ${DOCKER_REGISTRY-}messageprocessor
    build:
      context: .
      dockerfile: src/Template.MessageProcessor/Dockerfile
